export const INJECTION_TOKENS = {
  // Ports
  CLOCK: Symbol('CLOCK'),
  TOKEN_ENCRYPTION: Symbol('TOKEN_ENCRYPTION'),
  AUTH: Symbol('AUTH'),
  
  // Repositories
  PROFILE_REPOSITORY: Symbol('PROFILE_REPOSITORY'),
  MEMBERSHIP_REPOSITORY: Symbol('MEMBERSHIP_REPOSITORY'),
  SOCIAL_ACCOUNT_REPOSITORY: Symbol('SOCIAL_ACCOUNT_REPOSITORY'),
  CONTENT_REPOSITORY: Symbol('CONTENT_REPOSITORY'),
  METRICS_REPOSITORY: Symbol('METRICS_REPOSITORY'),
  SYNC_JOB_REPOSITORY: Symbol('SYNC_JOB_REPOSITORY'),
  RANKING_REPOSITORY: Symbol('RANKING_REPOSITORY'),
  AUDIT_REPOSITORY: Symbol('AUDIT_REPOSITORY'),
  SETTINGS_REPOSITORY: Symbol('SETTINGS_REPOSITORY'),
  OAUTH_STATE_REPOSITORY: Symbol('OAUTH_STATE_REPOSITORY'),
  
  // Social providers
  INSTAGRAM_PROVIDER: Symbol('INSTAGRAM_PROVIDER'),
  TIKTOK_PROVIDER: Symbol('TIKTOK_PROVIDER'),
  SOCIAL_PROVIDER_FACTORY: Symbol('SOCIAL_PROVIDER_FACTORY'),
} as const;
